# Tests are run on every commit except master branch updates
# where tests are also complimented by coverage analysis (coveralls)!

language: node_js
node_js: stable
services:
  - docker
cache:
  directories:
    - node_modules


jobs:
  include:
    - stage: Test
      if: branch != master
      name: Run backend tests
      before_install:
        - cd server
      script:
        - echo "TODO Write backend tests!"
    - stage: Test
      if: branch != master
      name: Run frontend tests
      before_install:
        - cd client
        - TZ=America/New_York
      script:
        - npm test


    - stage: Test and produce coverage (uploaded to coveralls.io)
      if: branch = master
      name: For backend app
      before_install:
        - cd server
      script: 
        - echo "TODO Again, write backend tests"
    - stage: Test and produce coverage (uploaded to coveralls.io)
      if: branch = master
      name: For frontend app
      before_install:
        - cd client
        - TZ=America/New_York
      script: >
        npm test -- 
        --coverage 
        --coverageReporters=text-lcov
        | coveralls ; test ${PIPESTATUS[0]} -eq 0
