---
language: node_js
node_js: stable
cache:
  directories:
    - node_modules

before_install:
  - cd ./client
  - export TZ=America/New_York

jobs:
  include:
    - stage: Test
      script: >
        npm test
    - stage: Build
      script:
        - npm run build
    - stage: Produce Coverage
      script: >
        npm test -- 
        --coverage 
        --coverageReporters=text-lcov
        | coveralls ; test ${PIPESTATUS[0]} -eq 0
    - stage: Deploy
      script: skip
      deploy:
        provider: heroku
        app: morning-scrubland-18259
        api_key: $ENC_HEROKU_API_KEY
        strategy: git
...
