---
language: node_js
node_js: stable
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      before_install:
        - cd ./client
      script: >
          npm test --
          --coverage
          --updateSnapshot
          --coverageReporters=text-lcov
          | coveralls
          ; test ${PIPESTATUS[0]} -eq 0
    - stage: build
      before_install:
        - cd ./client
      script:
        - npm run build
...
