version: "3"
services:

  backend:
    image: "arkadyt/wnetb:latest"
    env_file:
      - ./wnetb.env
    ports: 
      - "5001:5000"
    depends_on:
      - db

  db:
    image: "mongo:4.0.5-xenial"
    ports:
      - "27017:27017"
    volumes:
      - "/home/arkadyt/volumes/mongodb:/data/db"
