version: "3.1"
services:

  api:
    image: arkadyt/wework:latest
    restart: always
    env_file:
      - ./.env
    ports: 
      - ${PORT}:5000
    depends_on:
      - db

  db:
    image: mongo:4.0.5-xenial
    restart: always
