version: "3.1"
services:

  backend:
    image: arkadyt/wnetb:latest
    restart: always
    env_file:
      - /home/arkadyt/code/private/env/wnetb.env
    ports: 
      - 5001:5000
    depends_on:
      - db

  db:
    image: mongo:4.0.5-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /home/arkadyt/volumes/mongodb:/data/db
