#!/bin/bash


# get vars (db.env is not used by db service itself)
source /home/arkadyt/code/private/env/wwnet/db.env
export MONGO_INITDB_ROOT_USERNAME MONGO_INITDB_ROOT_PASSWORD


# restore
echo ::: restoring socnet.arkadyt.com\'s database from backup... :::
mongorestore \
  --drop \
  --preserveUUID \
  --restoreDbUsersAndRoles \
  --db=socnet \
  --host=localhost:27019 \
  --username=$MONGO_INITDB_ROOT_USERNAME \
  --password=$MONGO_INITDB_ROOT_PASSWORD \
  /home/arkadyt/code/dotfiles/cloud/dbrestore/socnet
