export const CREATING_PROFILE = 'CREATING_PROFILE'
export const ADDING_EXPERIENCE = 'ADDING_EXPERIENCE'
export const ADDING_EDUCATION = 'ADDING_EDUCATION'
export const ADDING_SM_LINKS = 'ADDING_SM_LINKS' // social media
export const DELETING_PROFILE = 'DELETING_PROFILE'